### ISSUE TITLE
Resume source

### ISSUE THREAD

**Issue by johnletey** [gillkyle/me#6]
@gillkyle Hate to bug you Kyle, as I know that you are busy! But I came across your website and found your resume, and I immediately fell in love with the design

How did you make it? Do you mind sharing the source of the PDF file?

**Comment by gillkyle** [comment]
Hey @johnletey! I used Sketch, I think I'll redo it in Figma at some point but Figma hasn't had great pdf exports options so that's what I was left with.

Here's the link to my sketch file I used: https://drive.google.com/open?id=1rsvPNcI9s9q5ovpRO9eVCYR_5t57ka0j

I really appreciate hearing that too, I've put many iterations into that design to try and get things just right 🙂
